# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool: 'RodsLocalPool'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      node --version;
      npm --version;
      ls

- task: Npm@1
  inputs:
    command: 'install'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      node --version;
      npm --version;
      ls

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      node --version;
      npm --version;
      ls

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
